language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  - composer install --prefer-source --no-interaction

script:
  - phpunit

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

matrix:
  fast_finish: true

notifications:
  slack: red-creek:bXLrIwXudNv0Jpi7pDtvjmNM
